#r "nuget: Azure.Identity"
//#r "nuget: Microsoft.ML.OnnxRuntimeGenAI"
#r "nuget: Microsoft.ML.OnnxRuntime.Gpu.Windows"
#r "nuget: System.Numerics.Tensors"
#r "nuget: FSharpX.Collections"
#r "nuget: Microsoft.Extensions.Http"
#r "nuget: Microsoft.Extensions.Hosting"
#r "nuget: Microsoft.DeepDev.TokenizerLib"
#r "nuget: Azure.Search.Documents"
#r "nuget: FSharp.SystemTextJson"
#r "nuget: FSharp.Data"
#r "nuget: FSharp.Collections.ParallelSeq"
#r "nuget: FSharp.Control.AsyncSeq"
#r "nuget: FsPickler.Json"
#r "nuget: azure.security.keyvault.secrets"
#r "nuget: Microsoft.Identity.Client.Broker"
#r "nuget: OpenCvSharp4.Windows"
#r "nuget: OpenCvSharp4.Extensions"
#r "nuget: System.Drawing.Common"
#r "nuget: Microsoft.SemanticKernel"
#r "nuget: NAudio"
#r "nuget: FFMpegCore"
#r "nuget: Plotly.NET"
#r "nuget: MathNet.Numerics.FSharp"
#r "nuget: FsPickler"

#load "../Vtt.fs"
#load "../Env.fs"
#load "../EmbedAudio.fs"
#load "../Secrets.fs"
#load "../Video.fs"
#load "../VisionApi.fs"
#load "../GraphApi.fs"

